const { join } = require('path');

// Note: If you use library-specific PostCSS/Tailwind configuration then you should remove the `postcssConfig` build
// option from your application's configuration (i.e. project.json).
//
// See: https://nx.dev/guides/using-tailwind-css-in-react#step-4:-applying-configuration-to-libraries
//
// PostCSS Configuration for Next.js
// @see https://nextjs.org/docs/app/building-your-application/styling/postcss
//
// For Turbopack compatibility with local plugins, we use require.resolve to get the absolute path
// @see https://nextjs.org/docs/app/building-your-application/styling/postcss#custom-plugins

// Use require.resolve to get the absolute path for Turbopack module resolution
// Turbopack resolves modules from its own context, so we need an absolute path string
const pluginPath = require.resolve('./postcss-fix-material-tailwind.js');

module.exports = {
  plugins: {
    tailwindcss: {
      config: join(__dirname, 'tailwind.config.js'),
    },
    autoprefixer: {},
    // Fix invalid CSS selectors generated by Material Tailwind React for Turbopack compatibility
    // Use absolute path string for local plugin (Turbopack requires this for proper module resolution)
    // This plugin runs after Tailwind CSS generates the CSS and fixes invalid selectors
    // before Lightning CSS (used by Turbopack) parses them
    // @see https://nextjs.org/docs/app/api-reference/turbopack#css-and-styling
    [pluginPath]: {},
  },
}
