packages:
  - 'apps/*'
  - 'libs/*'

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  cpu-features: set this to true or false
  esbuild: true
  less: false
  msw: false
  nx: true
  protobufjs: set this to true or false
  sharp: true
  ssh2: set this to true or false
  unrs-resolver: true
