package com.pml.booking.infrastructure.gateway.domain;

import java.math.BigDecimal;

/**
 * Provider-agnostic mobile money payment request.
 * <p>
 * No vendor-specific fields - those are handled by adapters.
 * All fields use generic naming conventions.
 */
public record MobileMoneyRequest(
        /**
         * Unique idempotency key to prevent duplicate payments.
         * Should be generated by the caller and remain consistent across retries.
         */
        String correlationId,

        /**
         * Phone number in E.164 format (+260XXXXXXXXX).
         */
        String phoneNumber,

        /**
         * Mobile network (auto-detected if null).
         * Will be determined from phoneNumber if not provided.
         */
        MobileNetwork network,

        /**
         * Payment amount.
         */
        BigDecimal amount,

        /**
         * Currency code (e.g., ZMW, USD).
         */
        String currency,

        /**
         * Human-readable payment description.
         * May be truncated by providers (typically 22-30 chars).
         */
        String description,

        /**
         * Webhook URL for async payment notifications.
         * Optional - provider may use configured default.
         */
        String callbackUrl,

        /**
         * Payer's name (for receipts and records).
         * Optional.
         */
        String payerName,

        /**
         * Payer's email (for receipts).
         * Optional.
         */
        String payerEmail
) {

    /**
     * Builder for MobileMoneyRequest.
     */
    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {
        private String correlationId;
        private String phoneNumber;
        private MobileNetwork network;
        private BigDecimal amount;
        private String currency = "ZMW";
        private String description;
        private String callbackUrl;
        private String payerName;
        private String payerEmail;

        public Builder correlationId(String correlationId) {
            this.correlationId = correlationId;
            return this;
        }

        public Builder phoneNumber(String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        public Builder network(MobileNetwork network) {
            this.network = network;
            return this;
        }

        public Builder amount(BigDecimal amount) {
            this.amount = amount;
            return this;
        }

        public Builder currency(String currency) {
            this.currency = currency;
            return this;
        }

        public Builder description(String description) {
            this.description = description;
            return this;
        }

        public Builder callbackUrl(String callbackUrl) {
            this.callbackUrl = callbackUrl;
            return this;
        }

        public Builder payerName(String payerName) {
            this.payerName = payerName;
            return this;
        }

        public Builder payerEmail(String payerEmail) {
            this.payerEmail = payerEmail;
            return this;
        }

        public MobileMoneyRequest build() {
            // Auto-detect network if not provided
            MobileNetwork detectedNetwork = network;
            if (detectedNetwork == null && phoneNumber != null) {
                detectedNetwork = MobileNetwork.fromPhoneNumber(phoneNumber);
            }

            return new MobileMoneyRequest(
                    correlationId,
                    phoneNumber,
                    detectedNetwork,
                    amount,
                    currency,
                    description,
                    callbackUrl,
                    payerName,
                    payerEmail
            );
        }
    }

    /**
     * Create a copy with updated network.
     */
    public MobileMoneyRequest withNetwork(MobileNetwork network) {
        return new MobileMoneyRequest(
                correlationId, phoneNumber, network, amount, currency,
                description, callbackUrl, payerName, payerEmail
        );
    }
}
